---
title: "Data Processing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#working directory
setwd("~/Yale/2022 Fall/Tobin RA")
# packages
library(tidyverse)
library(readxl)
```
 

```{r warning=FALSE}
# loading in data
df_2015 <- rbind(read_xlsx("data/2015.xlsx"), read_xlsx("data/2015b.xlsx"))
df_2016 <- read_xlsx("data/2016.xlsx")
df_2017 <- rbind(read_xlsx("data/2017.xlsx"), read_xlsx("data/2017b.xlsx"))
df_2018 <- rbind(read_xlsx("data/2018a.xlsx"),
                 read_xlsx("data/2018b.xlsx"),
                 read_xlsx("data/2018c.xlsx"))
df_2019 <- rbind(read_xlsx("data/2019a.xlsx"),
                 read_xlsx("data/2019b.xlsx"),
                 read_xlsx("data/2019c.xlsx"))
df_2020 <- read_xlsx("data/2020.xlsx")

# saving data for easy loading next time
# use load() to load data
save(
  df_2015,
  df_2016,
  df_2017,
  df_2018,
  df_2019,
  df_2020,
  file="allyears.RData"
)

# basic structure
dim(df_2015)
names(df_2015)
str(df_2015)

```

```{r}
### response count stats
nrow(df_2015)
nrow(df_2016)
nrow(df_2017)
nrow(df_2018)
nrow(df_2019)
nrow(df_2020)
# number of responses changes a lot! Is this an issue?

### checking if there are duplicates within each year
length(unique(df_2015$PID))-nrow(df_2015)
length(unique(df_2016$PID))-nrow(df_2016)
length(unique(df_2017$PID))-nrow(df_2017)
length(unique(df_2018$PID))-nrow(df_2018)
length(unique(df_2019$PID))-nrow(df_2019)
length(unique(df_2020$PID))-nrow(df_2020)
# no duplicates within year
```


```{r}
### getting consistent gender labels ###


# is there a more elegant way to do this???
df_2015$GENDER[!(df_2015$GENDER %in% c("Female", "Male", NA))] <- "Other"
df_2016$GENDER[!(df_2016$GENDER %in% c("Female", "Male", NA))] <- "Other"
df_2017$GENDER[!(df_2017$GENDER %in% c("Female", "Male", NA))] <- "Other"
df_2018$GENDER[!(df_2018$GENDER %in% c("Female", "Male", NA))] <- "Other"
df_2019$GENDER[!(df_2019$GENDER %in% c("Female", "Male", NA))] <- "Other"
df_2020$GENDER[!(df_2020$GENDER %in% c("Female", "Male", NA))] <- "Other"

### below doesn't work
# dfList <- list(df_2015, df_2016, df_2017, df_2018, df_2019, df_2020)
# lapply(dfList, function(x){
#   x$GENDER[!(x$GENDER %in% c("Female", "Male", NA))] <- "Other"
# })
# 
# table(df_2015$GENDER)

```

```{r}
### sanity check for gender counts ###

genderdist <- function(dat){
  hist1 <- ggplot(dat, aes(x=GENDER)) +
    geom_bar(stat="count", width=0.7, fill="steelblue")
  return(hist1)
}

genderdist(df_2015)
genderdist(df_2016)
genderdist(df_2017)
genderdist(df_2018)
genderdist(df_2019)
genderdist(df_2020)
```



```{r}
# subsetting for numeric data only
num2015 <- select_if(df_2015, c("SALARY", "HOURLY_RATE", "HOURLY_WORKWEEK", "AGE", "FAIR_PAY"))

names(df_2015)
names(df_2020)

```


 
 